version: "3.9"
services:
  database:
    image: postgres
    container_name: tgexample
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: testdb
